#!/bin/csh

#PBS -N batch_job_orig_mirror_old_interleaving
#PBS -r n
#PBS -e /nobackup/gridiron/hadron/li479/log/batch_job_orig_mirror_old_interleaving.err
#PBS -o /nobackup/gridiron/hadron/li479/log/batch_job_orig_mirror_old_interleaving.log
#PBS -m abe
#PBS -M wenliang.billlee@gmail.com
#PBS -q hadron
#PBS -l walltime=60:00:00
## the limitation of our geat4 simulation is 500000 particles
## 60 hour CPU time is the average running period

date

cd /backedup/gridiron/hadron/li479/geant4/SHMS_HeavyGasCer/batch_job_orig_mirror_old_interleaving
shms_hvgascer batch_500000.mac

date
exit
